# Generated by Django 3.0.5 on 2020-05-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copurchase',
            options={'managed': False},
        ),
    ]
